/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;
import java.awt.Font;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shadow
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    Reloj reloj = new Reloj();
    Lista lista = new Lista();
    RoundRobin rr = new RoundRobin();
    boolean bandera;
    int quantum = 10;
    int c = 0;
    int tmemoria = 500;

    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        reloj.start();
        rr.start();
        tmemoria = tmemoria - 50;
        tmem.setText(String.valueOf(tmemoria));
//                    
    }

    public class Reloj extends Thread {

        Calendar obtener;

        @Override
        public void run() {
            while (true) {
                obtener = Calendar.getInstance();

                hora.setText(String.valueOf(obtener.get(Calendar.HOUR_OF_DAY)) + " :");

                if (obtener.get(Calendar.MINUTE) < 10) {
                    minutos.setText(String.valueOf("0" + obtener.get(Calendar.MINUTE)) + " :");
                } else {
                    minutos.setText(String.valueOf(obtener.get(Calendar.MINUTE)) + " :");
                }

                if (obtener.get(Calendar.SECOND) < 10) {
                    segudos.setText(String.valueOf("0" + obtener.get(Calendar.SECOND)));
                } else {
                    segudos.setText(String.valueOf(obtener.get(Calendar.SECOND)));
                }

                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public class RoundRobin extends Thread {

        @Override
        public void run() {
            while (true) {
                try {
                    nodo aux = lista.getInicio();
                    if (lista.getInicio() != null) {
                        for (int i = 0; i <= lista.getTamanio(); i++) {
                            System.out.println("P" + aux.getNumero() + " Tejec" + aux.getDuracion());

                            if (aux.getDuracion() <= quantum) {
                            }
                            
                            jLabelPrejec.setText("P" + aux.getNumero());
                            Thread.sleep(aux.getDuracion() * 1000);
                            if (aux.getSiguiente() == null) {
                                break;
                            }
                            aux = aux.getSiguiente();
                        }
                    } else {

                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    public void Ingresar(){
    DefaultTableModel modelo=(DefaultTableModel) memoria.getModel();
    Object[] miTabla = new Object[1];
    miTabla[0]= "proceso  " + c;
    modelo.addRow(miTabla);
    memoria.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hora = new javax.swing.JLabel();
        minutos = new javax.swing.JLabel();
        segudos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jLabelPrejec = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        memoria = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tmem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 446, 45, 53));

        minutos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(minutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 446, 45, 53));

        segudos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(segudos, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 446, 74, 53));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("RELOJ EN TIEMPO REAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 416, -1, 24));

        jButtonCrear.setText("Agregar");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 75, -1));

        jLabelPrejec.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelPrejec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrejec.setText("PN");
        getContentPane().add(jLabelPrejec, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 110, 50));

        jLabel2.setText("Calendarizador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        memoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso"
            }
        ));
        jScrollPane3.setViewportView(memoria);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 540));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("    S.O.");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Memoria Restante");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, -1, 30));

        tmem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tmem.setText("500");
        getContentPane().add(tmem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        int duracion = (int) (Math.random() * 11) + 5;
        if(tmemoria>=duracion){
        tmemoria = tmemoria - duracion;
        tmem.setText(String.valueOf(tmemoria));
        c += 1;
        lista.insertar(c, duracion);
  Ingresar();}
        
        
        else{JOptionPane.showMessageDialog(null, "memoria insuficiente");}


    }//GEN-LAST:event_jButtonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPrejec;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable memoria;
    private javax.swing.JLabel minutos;
    private javax.swing.JLabel segudos;
    private javax.swing.JLabel tmem;
    // End of variables declaration//GEN-END:variables
}
